---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
      MOCHA_FILE: "reports/mocha.xml"
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v3-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v3-yarn-{{checksum ".circleci/config.yml"}}
      - run: yarn
      - run: yarn add -D nyc@13 @oclif/nyc-config@1 mocha-junit-reporter@1
      - run: ./bin/run --help
      - run: |
          mkdir -p reports
          $NYC yarn test --reporter mocha-junit-reporter
          $NYC report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
      - store_test_results: &store_test_results
          path: ~/cli/reports
  node-10:
    <<: *test
    docker:
      - image: node:10
  node-8:
    <<: *test
    docker:
      - image: node:8

workflows:
  version: 2
  "@oclif/plugin-plugins":
    jobs:
      - node-latest
      - node-10
      - node-8
